apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsserver
spec:
  selector:
    matchLabels:
      app: wsserver
  template:
    metadata:
      labels:
        app: wsserver
    spec:
      containers:
      - name: wsserver
        image: deepvoid/wsserver
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "1"
          limits:
            memory: "256Mi"
            cpu: "2"
