apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub
  labels:
    app: pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
    spec:
      containers:
      - name: pub
        image: deepvoid/pub
        imagePullPolicy: Always
        env:
          - name: PUB_HOST
            value: "*"
          - name: PUB_PORT
            value: "5555"
        ports:
        - containerPort: 5555
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
