apiVersion: v1
kind: Service
metadata:
  name: pub-headless
  labels:
    app: pub
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: pub
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
      name: pub
