apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pub
spec:
  selector:
    matchLabels:
      app: pub
  serviceName: pub-headless
  replicas: 2
  template:
    metadata:
      labels:
        app: pub
    spec:
      containers:
      - name: pub
        image: deepvoid/pub
        imagePullPolicy: Always
        env:
          - name: PUB_HOST
            value: "*"
          - name: PUB_PORT
            value: "5555"
        ports:
        - containerPort: 5555
          name: web
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
