apiVersion: v1
kind: Service
metadata:
  name: hub
  labels:
    app: hub
spec:
  type: LoadBalancer
  selector:
    app: hub
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
      name: http